### ISSUE TITLE
Add the cubed-sphere projections to Atlas

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/atlas#15]
Add the cubed sphere projections to Atlas

- [x] Equidistant 
- [x] Equiangular
- [ ] Equidistant FV3

**Comment by MarekWlasak** [comment]
Note that equidistant FV3 projection is not yet part of the ecmwf develop.

**Comment by MarekWlasak** [comment]
Going into Ice box as it has been decided by JCSDA that Met Office are not responsible for creating the fv3 cubed-sphere projection class.

**Comment by MarekWlasak** [comment]
Moved to icebox as JCSDA agreed that equidistant-fv3 projection is not MetOffice's responsibility.

**Comment by shlyaeva** [comment]
@danholdaway do you have or know of plans for the equidistant fv3 projection?

**Comment by danholdaway** [comment]
Not in the immediate. Though it might become more important if we see efficiency issues in the interpolation around the B matrix operators.
