### ISSUE TITLE
CMake install process does not include the Fortran modules

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/atlas#17]
When you build atlas as part of your bundle, access to the Fortran modules is there and the build works. 

However, if you build atlas separately and install (``make install``) somewhere (such as with jedi-stack), and simply reference it from your bundle, the build does not work due to the Fortran modules being missing.

It appears that the Fortran modules are not getting included in the "install" target.

**Comment by shlyaeva** [comment]
is this still an issue?

**Comment by shlyaeva** [comment]
@srherbener: is it OK to close this, or is issue is still relevant?

**Comment by srherbener** [comment]
@shlyaeva, I tested this today and it is working now. Some of the recent CMake updates appear to have fixed this. I'll go ahead a close this.
