### ISSUE TITLE
Add the cubed-sphere domain decomposition

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/atlas#21]
Once the Grid, Projection and MeshGenerator classes have been added for the Cubed-Sphere grid it will be necessary to add the domain decomposition.

**Comment by MarekWlasak** [comment]
This has been done for cell centers

**Comment by MarekWlasak** [comment]
This was done for cell-centered grid.

**Comment by shlyaeva** [comment]
@danholdaway, @MarekWlasak can this issue be closed now?

**Comment by MarekWlasak** [comment]
It will work also for the nodes of the dual of the cubed-sphere mesh.  So far, unless LFRic changes its mind to give us horizontally staggered winds we are all done.  I think that there may be some more work for fv3 as I think that the winds are staggered, but I am not sure.  First fv3 needs to create its own atlas projection to utilize what we have done.  @danholdaway what do you think about this? There may be some extra tuning of the cubed-sphere decomposition for when we need to link it to LFRic's tangent linear model, but that will happen in a few month's time.

**Comment by MarekWlasak** [comment]
So in summary I think it should be closed (for now)

**Comment by danholdaway** [comment]
I agree that we should close this, and will do so now. We can reopen more specific FV3 issues if/when the time comes to make things work for FV3.
