### ISSUE TITLE
Add Fortran API to Cubed-Sphere classes

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/atlas#22]
Need to add the Fortran API to the cubed-sphere classes so cubed-sphere grids could be implemented and accessed from Fortran code.

**Comment by shlyaeva** [comment]
@danholdaway is this active?

**Comment by danholdaway** [comment]
I think it would be needed but I don't have time to work on that at the moment. @MarekWlasak @odlomax are you planning to work on this or maybe already have?

**Comment by shlyaeva** [comment]
@MarekWlasak, @odlomax: a follow-up on Dan's question. Do you know the status of this issue?

**Comment by shlyaeva** [comment]
I am going to close this issue, please reopen if needed.
