### ISSUE TITLE
Address Willem's Comments in regards to the cubed sphere grid, projection and mesh gen

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/atlas#26]

**Comment by MarekWlasak** [comment]
@MarekWlasak  and @odlomax are iterating to this in a branch feature/cubed-sphere-base.

@MarekWlasak  is dealing with the continuous xy projection space, while @odlomax is working on the rest

**Comment by MarekWlasak** [comment]
https://github.com/JCSDA-internal/atlas/pull/38  -deals with the continuous xy projection space.
