### ISSUE TITLE
Compile failure when built against CGAL

### ISSUE THREAD

**Issue by DJDavies2** [JCSDA-internal/atlas#3]
I am getting the following compile failure when building ATLAS develop with CGAL (i.e. -DENABLE_TESSELATION=ON):

`In file included from /home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/StructuredInterpolation2D.tcc:31:0,
                 from /home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/StructuredInterpolation2D.h:87,
                 from /home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/Cubic2D.h:13,
                 from /home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/Cubic2D.cc:11:
/home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/StructuredInterpolation2D.tcc: In instantiation of 'void atlas::interpolation::method::StructuredInterpolation2D<Kernel>::setup(const atlas::FunctionSpace&) [with Kernel = atlas::interpolation::method::CubicHorizontalKernel]':
/home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/StructuredInterpolation2D.tcc:92:10:   required from 'void atlas::interpolation::method::StructuredInterpolation2D<Kernel>::setup(const atlas::FunctionSpace&, const atlas::FunctionSpace&) [with Kernel = atlas::interpolation::method::CubicHorizontalKernel]'
/home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/Cubic2D.cc:32:1:   required from here
/home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/interpolation/method/structured/StructuredInterpolation2D.tcc:149:38:   in constexpr expansion of 'atlas::NormaliseLongitude()'
/home/h01/frwd/cylc-run/AtlasCgalFailure/work/1/build_atlas__lfric_gnu_rhel7_debug/atlas/src/atlas/util/NormaliseLongitude.h:20:66: error: '(3.6e+2 - 9.9999999999999994e-12)' is not a constant expression
     constexpr NormaliseLongitude() : west_( -eps_ ), east_( 360. - eps_ ) {}
                                                             ~~~~~^~~~~~
`
I am using gcc 6.1.0, CGAL 5.0, cmake 3.13.4.

Compilation is fine without CGAL.  The difference is that the CGAL cmake configs insert -frounding-math into the c++ flags which means that the above expression in NormaliseLongitude.h becomes invalid (at least according to gcc).  There is some discussion of this here: https://github.com/CGAL/cgal/issues/3180.  They basically blame it on gcc and they are not going to change CGAL.  Note that although I am using a somewhat old version of gcc the versions referenced in the CGAL issue are more recent and still appear to have the problem, although I haven't tested.

The -frounding-math option can be overriden by -fno-rounding-math, but I don't see a way of actually passing this via the ecbuild command line.  Setting -DCMAKE_CXX_FLAGS doesn't work as the flags are in the wrong order, i.e. the g++ command ends up being something like

`g++ .... -fno-rounding-math .. -frounding-math ...`

In the end I can work around this by manually removing -frounding-math from src/atlas/CMakeFiles/atlas.dir/flags.make.  It is unclear what the consequences of this are.

**Comment by markjolah** [comment]
@DJDavies2 I am getting success with:
* CGal-4.11.3
* gcc-9.2.0
* cmake-3.16.4

Not seeing either of these errors.  Have you tried the 4.x series CGal?

**Comment by DJDavies2** [comment]
I tried with CGal-4.11.3 and cmake-3.16.4 and it did indeed work.  It appears that the problem is with later versions of CGal.

**Comment by shlyaeva** [comment]
@DJDavies2 is it OK to close this issue?

**Comment by DJDavies2** [comment]
Yes, that is fine.
