### ISSUE TITLE
Cmake failure when attempting to compile against CGAL

### ISSUE THREAD

**Issue by DJDavies2** [JCSDA-internal/atlas#4]
I am getting the following ecbuild/cmake error when trying to compile ATLAS against CGAL (via -DENABLE_TESSELATION=ON):

`CMake Error at CMakeLists.txt:141 (set_target_properties):
  set_target_properties can not be used on an ALIAS target.
`
Cmake version 3.13.4, CGAL version 5.0, ATLAS develop.  My ecbuild command contains -DCgal_DIR=/path/to/cgal/install/lib64/CGAL/cmake, I have looked at the trace and it seems to be correctly finding the CGALConfig.cmake file and its friends.

Line 141 of CMakeLists.txt is

`      set_target_properties( CGAL::CGAL PROPERTIES INTERFACE_COMPILE_OPTIONS "" )
`
I can work around this by removing lines from ATLAS's CMakeLists.txt files:

line 141 of CMakeLists.txt
lines 234-237 of src/atlas/CMakeLists.txt

but I guess this is not the desired solution.

**Comment by DJDavies2** [comment]
It seems that replacing CGAL::CGAL with plain CGAL in CMakeLists.txt fixes the issue.  This is consistent with the error message, and this documentation:

https://cmake.org/cmake/help/v3.9/command/add_library.html#alias-libraries

which both say that what is being done currently is invalid.  There is a reference in the code comments to an ECMWF ATLAS Jira ticket 193 which I guess would be:

https://jira.ecmwf.int/browse/ATLAS-193

but I don't have permission to view it.

**Comment by mmiesch** [comment]
is this fixed by https://github.com/JCSDA-internal/jedi-stack/pull/70 ?

**Comment by DJDavies2** [comment]
The modifications to the dependencies file help fix the problem.
