### ISSUE TITLE
Cubed-sphere tiling

### ISSUE THREAD

**Issue by MarekWlasak** [JCSDA-internal/atlas#41]

**Comment by MarekWlasak** [comment]
PR created at ecmwf.

**Comment by MarekWlasak** [comment]
PR for part 1 has been done ( creating a tile class factory)  Almost completed the grid part,

**Comment by MarekWlasak** [comment]
Grid part was completed and added to the ecmwf atlas PR #67.

**Comment by MarekWlasak** [comment]
In review at ecmwf

**Comment by wdeconinck** [comment]
This is merged upstream and can be closed.
