### ISSUE TITLE
Ability to enable OpenMP is now broken with addition of atlas repo

### ISSUE THREAD

**Issue by jmrosinski** [JCSDA-internal/atlas#6]
Trying to build ufo-bundle with these lines uncommented in top-level CMakeLists.txt file:

```
ecbuild_add_option( FEATURE OMP
                    DEFAULT ON
                    DESCRIPTION "Use OpenMP" )

```

used to work fine, appropriately enabling OpenMP in the CRTM code I've been working with. But now with the latest addition of the atlas repo, attempts to build the ufo-bundle are failing with this:

```
CMake Error at /home/rosinski/ecbuild/cmake/ecbuild_log.cmake:196 (message):
  CRITICAL - Feature OMP cannot be enabled -- following condition was
  not met: OpenMP_Fortran_FOUND OR OpenMP_CXX_FOUND
Call Stack (most recent call first):
  /home/rosinski/ecbuild/cmake/ecbuild_add_option.cmake:237 (ecbuild_critical)
  atlas/CMakeLists.txt:98 (ecbuild_add_option)

```

Does anyone know how to fix this? I can't seem to find where OpenMP_Fortran_FOUND or OpenMP_CXX_FOUND get set.

Giving best guess as to appropriate assignees. Feel free to adjust as appropriate.

**Comment by jmrosinski** [comment]
FYI commenting out the following lines in atlas/CMakeLists.txt resulted in a successful build. This is probably not the right solution, but hopefully points in the right direction.

```
#ecbuild_add_option( FEATURE OMP
#                   DESCRIPTION "support for OpenMP shared memory parallelism"
#                    CONDITION OpenMP_Fortran_FOUND OR OpenMP_CXX_FOUND )
#ecbuild_add_option( FEATURE OMP_Fortran
#                    DESCRIPTION "support for Fortran OpenMP shared memory parallelism"
#                    CONDITION HAVE_OMP AND OpenMP_Fortran_FOUND )
#
#ecbuild_add_option( FEATURE OMP_CXX
#                    DESCRIPTION "support for CXX OpenMP shared memory parallelism"
#                    CONDITION HAVE_OMP AND OpenMP_CXX_FOUND )
#if( TARGET OpenMP::OpenMP_CXX )
#  set( OMP_CXX OpenMP::OpenMP_CXX )
#endif()
#if( TARGET OpenMP::OpenMP_Fortran )
#  set( OMP_Fortran OpenMP::OpenMP_Fortran )
#endif()

```

**Comment by markjolah** [comment]
@jmrosinski What CMake version are you running?  Also what compiler?

**Comment by jmrosinski** [comment]
cmake version 3.10.2
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by markjolah** [comment]
You will need CMake >=3.11 to use OpenMP with Atlas, and therefore also with any of the bundles that include atlas.

From the main Atlas `CMakeLists.txt`
```
if( "${CMAKE_VERSION}" VERSION_LESS "3.11" )
  if( ENABLE_OMP )
    ecbuild_warn( "OpenMP only supported with CMake 3.11 onwards" )
  endif()
else()
  find_package( OpenMP COMPONENTS CXX ${Fortran} )
endif()
```

**Comment by jmrosinski** [comment]
OK thanks I guess I should have been able to find that myself. I'll either continue with the commented-out approach I've been using, or build a newer cmake from scratch (3.10.2 is the latest that the most recent Linux mint is willing to install with "apt install").

**Comment by markjolah** [comment]
@jmrosinski Yeah I was worried about Ubuntu 18 being so far behind.  I looked and it doesn't look like they have backported any newer CMake's.  It's not hard to build it yourself, but we maybe should be providing some documentation on how to do that.  The other option is to use the singularity container which will have the newer CMake.  If you do build it yourself, the newest possible version will be preferred.

**Comment by mmiesch** [comment]
There is already a build script in jedi-stack for CMake.  I use it fairly often.
