### ISSUE TITLE
Do we still need this repo?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/atlas#95]
## Description

We've switch back to the authoritative repository a while ago ...

> This branch is [4 commits ahead](https://github.com/JCSDA-internal/atlas/compare/ecmwf:atlas:develop...release-stable), [704 commits behind](https://github.com/JCSDA-internal/atlas/compare/release-stable...ecmwf:atlas:develop) ecmwf:develop.

Do we need to keep this repo alive? Or archive? Or delete? What about the four commits that we are ahead, are they needed (doesn't look like)?

**Comment by svahl991** [comment]
I'm not aware of any need to keep this repository.

**Comment by ytremolet** [comment]
I don't think it's needed.

**Comment by climbfuji** [comment]
Ok, I am going to close this issue and delete the repo (a fork of the authoritative repo).
